### ISSUE TITLE
Is there a route for FitQuest

### ISSUE THREAD

**Issue by SagaraBattousai** [luke0x90/thegymgroup-api#3]
Is there a route for FitQuest? I've tried guessing to no avail and using api.fitquest.com is a pain. Any chance there are other routes or ways to discover them?

**Comment by luke0x90** [comment]
FitQuest is provided as a service by https://www.fqscore.com/ and is not natively supported in the app. Using Jadx you can see this in the decompiled APK, it essentially just iframes the The Gym "members area" part of the website.

Using mitmproxy, I pulled the following routes which you can scrape:

`https://embed.fqscore.com/Widgets/v1/Carousel?tkn=<token_value>`

The token here is a JWT Token, which is retrieved via a request to `GET /member-area/_next/data/<redacted>/your-gym/fitquest-area.json`. The `<redacted>` is just a build ID that you can get from `GET /member-area/`.

You cannot make a request to this URL using the mobile authentication token, you need to authenticate normally first. All auth cookies required for the ` /member-area/_next/data/<redacted>/your-gym/fitquest-area.json` call are set during the first authenticated call to `GET /member-area/`.

You can convert a mobile auth token into one you can use with the web via `https://www.thegymgroup.com/member-area/api/auth/me`

The issue is that there is no nice API route for the data as JSON. You will have to extract it manually from the DOM. The data is right at the bottom of the HTML under `biaChartsWidgetInit`.


Probably something selenium would be able to do quickly. Good luck!

**Comment by SagaraBattousai** [comment]
This is excellent advice, thank you so much!

It's been a long time since I've done this kind of thing but you've given me a great headstart!
